#!/bin/bash
set -e

# Setup Icelab dotfiles
echo "Fetching icelab/dotfiles from GitHub…"
if [ ! -d "$HOME/.dotfiles-icelab" ]; then
  echo "Cloning to ~/.dotfiles-icelab:"
  git clone $Q "https://github.com/icelab/dotfiles" ~/.dotfiles-icelab
else
  (
    cd ~/.dotfiles-icelab
    git pull $Q --rebase --autostash
  )
fi
cd ~/.dotfiles-icelab
./script/setup
echo "OK"

# Install standard homebrew packages
echo "Installing standard homebrew packages…"
brew bundle --file=- <<EOF
tap "heroku/brew"
brew "asdf"
brew "gpg"
brew "heroku"
EOF
echo "OK"

# Install/bootstrap standard asdf plugins
echo "Installing standard asdf plugins…"
if [ -z "$(asdf plugin-list | grep ruby)" ]; then
  asdf plugin-add ruby
fi
if [ -z "$(asdf plugin-list | grep nodejs)" ]; then
  asdf plugin-add nodejs
fi
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
echo "OK"

# Switch to zsh (but only if the user is on a standard bash shell)
if [ ! -z "$(dscl . -read /Users/$USER UserShell | grep /bin/bash)" ]; then
  echo "Switching shell to zsh…"
  chsh -s /bin/zsh
  echo "OK"
fi
