#!/bin/bash
set -e

# Setup shared dotfiles
echo "Fetching cultureamp/web-team-dotfiles from GitHub…"
if [ ! -d "$HOME/.dotfiles-web-team" ]; then
  echo "Cloning to ~/.dotfiles-web-team:"
  git clone $Q "https://github.com/cultureamp/web-team-dotfiles" ~/.dotfiles-web-team
else
  (
    cd ~/.dotfiles-web-team
    git pull $Q --rebase --autostash
  )
fi
cd ~/.dotfiles-web-team
./script/setup
echo "OK"

# Install standard homebrew packages
echo "Installing standard homebrew packages…"
brew bundle --file=- <<EOF
brew "asdf"
brew "gpg"
EOF
echo "OK"

# Install/bootstrap standard asdf plugins
echo "Installing standard asdf plugins…"
if [ -z "$(asdf plugin-list | grep ruby)" ]; then
  asdf plugin-add ruby
fi
if [ -z "$(asdf plugin-list | grep nodejs)" ]; then
  asdf plugin-add nodejs
fi
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
echo "OK"
